# Generated by Django 5.1 on 2024-08-11 12:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='projects/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='services/'),
        ),
    ]
